dataset_path: /root/Desktop/workspace/miso/hub/datasets/lavis/coco
dataset_name: null
dataset_kwargs:
  data_files: {"default": "chair_annotations/annotations_coco_500.jsonl"}
  token: True
task: "chair_max64_save_attention"
test_split: default
output_type: generate_until
process_docs: !function utils.process_docs
doc_to_visual: !function utils.chair_doc_to_visual
doc_to_text: !function utils.chair_doc_to_text
doc_to_target: !function utils.chair_doc_to_target
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.chair_process_results
metric_list:
  - metric: CHAIR
    aggregation: !function utils.chair_agg_chair
    higher_is_better: false

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  plm:
    pre_prompt: ""
    post_prompt: ""
metadata:
  version: 0.0
  no_system_prompt: false
  vqa_save_attention: true
  return_dict_in_generate: true
  output_attentions: true
  output_dir: ./logs
